### ISSUE TITLE
This theme is cool

### ISSUE THREAD

**Issue by warnotte** [maxlefou/hugo.386#5]
I'have nothing to say. This theme is cool.
Maybe bootstrap upgrade to V5 ?

**Comment by jmfergeau** [comment]
That depends of [bootstra.386](https://github.com/kristopolous/BOOTSTRA.386)'s dev.
There's already a branch of hugo.386 based on bootstrap 4 since this one was more stable, but leads to some drastic changes in the design. [Fell free to check it out here](https://github.com/maxlefou/hugo.386/tree/v3).

**Comment by warnotte** [comment]
Thanks you for the informations.
